//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchEngine.UtilityClass {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchEngine.UtilityClass.ResourceFile", typeof(ResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3d45386b-fd27-4fb1-bcc3-f6c33d749a78.
        /// </summary>
        internal static string BingCustomConfigId {
            get {
                return ResourceManager.GetString("BingCustomConfigId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocp-Apim-Subscription-Key.
        /// </summary>
        internal static string BingOcpApimSubscriptionKey {
            get {
                return ResourceManager.GetString("BingOcpApimSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bf10862e60f946e0b21f257263e052b4.
        /// </summary>
        internal static string BingSubscriptionKey {
            get {
                return ResourceManager.GetString("BingSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://api.cognitive.microsoft.com/bingcustomsearch/v7.0/search?.
        /// </summary>
        internal static string BingUrl {
            get {
                return ResourceManager.GetString("BingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AIzaSyBr5jnOdpRhx_OZ6DLyqq6LqdI8qp0g67Y.
        /// </summary>
        internal static string GoogleApiKey {
            get {
                return ResourceManager.GetString("GoogleApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 011956850629618895793:ln8ptxrzhaa.
        /// </summary>
        internal static string GoogleSearchEngineId {
            get {
                return ResourceManager.GetString("GoogleSearchEngineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SearchEngine1.
        /// </summary>
        internal static string ParameterKey1 {
            get {
                return ResourceManager.GetString("ParameterKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SearchEngine2.
        /// </summary>
        internal static string ParameterKey2 {
            get {
                return ResourceManager.GetString("ParameterKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SearchEngine.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
    }
}
